server:
  port: 8080

push:
  vapid:
    publicKey: "BPblscWtfIcjakPrRsHINaRYA6mIdNlIXJATdiDoZ-VO8G_T7kwOCXdsgomGziE"
    privateKey: "WS7QZZJJJs9GbSAAtQ3a93LfYqrWuOoYig"
    subject: mailto:dev@example.com